// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTwSio1XDRo-NzN1T46UN8omfCz5spG8E',
    appId: '1:452565842878:web:396f18104d4b3cee1a17ef',
    messagingSenderId: '452565842878',
    projectId: 'jenskackapp',
    authDomain: 'jenskackapp.firebaseapp.com',
    storageBucket: 'jenskackapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6usa_94uYE3glj7MILuEFOnyKfYZFL2s',
    appId: '1:452565842878:android:f8f6725677c674a11a17ef',
    messagingSenderId: '452565842878',
    projectId: 'jenskackapp',
    storageBucket: 'jenskackapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0OvDV2gHgeKZTPCM78Qf0p7wQfJst77k',
    appId: '1:452565842878:ios:f47c33f54c719c171a17ef',
    messagingSenderId: '452565842878',
    projectId: 'jenskackapp',
    storageBucket: 'jenskackapp.appspot.com',
    iosBundleId: 'com.example.kurs1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0OvDV2gHgeKZTPCM78Qf0p7wQfJst77k',
    appId: '1:452565842878:ios:f47c33f54c719c171a17ef',
    messagingSenderId: '452565842878',
    projectId: 'jenskackapp',
    storageBucket: 'jenskackapp.appspot.com',
    iosBundleId: 'com.example.kurs1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTwSio1XDRo-NzN1T46UN8omfCz5spG8E',
    appId: '1:452565842878:web:6950e6e175acdbe11a17ef',
    messagingSenderId: '452565842878',
    projectId: 'jenskackapp',
    authDomain: 'jenskackapp.firebaseapp.com',
    storageBucket: 'jenskackapp.appspot.com',
  );

}